\echo '\nAliases:\n'
\echo '\t:users\t\tShow users'
\echo '\t:conninfo\tServer connections'
\echo '\t:showlocks\tShow table locks'
\echo '\t:showrunning\tShow running processes'
\echo '\t:tablesize\tTable sizes'
\echo '\t:usergroups\tShow users and their groups'
\echo '\t:groupprivs\tShow group priveleges'
\echo '\t:showtables\tShow all tables'
\echo '\t:showviews\tShow all views'
\echo '\t:gen_view_ddl\tCreates view admin.v_generate_tbl_ddl'
\echo '\t:gen_view_ext\tCreates view admin.v_extended_table_info'
\echo
