---

services:
  - docker
before_install:
  - docker build -f .Dockerfile-ci --pull --tag dotfiles/base .
  - sed -i '/git@github.com/, /github.com\// s/^/#/' configs/git/gitconfig
script:
  - 'docker run --tty --volume `pwd`:/home/shaw/dotfiles dotfiles/base dotfiles/install.sh'

