version: '3.6'

services:
  dotfiles:
    container_name: dotfiles
    build:
        # this context is relative to the location of the docker-compose.shared.yml
        # (i.e., $CL_HOME/dev/docker)
        context: .
        dockerfile: .Dockerfile-ci
    user: shaw
    volumes:
      - .:/home/shaw/dotfiles:delegated
    command: ["/bin/bash", "-c", "echo Container ready for use. Feel free to ctrl-c. Container will stick around! && while true ; do sleep 3600; done"]
