#
# Loaded for each terminal and sourced at login by ~/.bash_profile.
#

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Enable programmable completion features (you don't need to enable this, if
# it's already enabled in /etc/bash.bashrc and /etc/profile sources
# /etc/bash.bashrc).
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

set -o vi                         # Run bash with vi keys instead of emacs
shopt -s checkwinsize
shopt -s histappend
shopt -s cdspell                  # Let bash help you change directories when you can't spell

export MANPAGER="nvim -c 'set ft=man' -"
export HISTCONTROL=ignoredups
export HISTSIZE=100000
export PROMPT_COMMAND='history -a'
export EDITOR=nvim
export TERM=xterm-256color                  # this is for solarized

export PATH=\
/usr/local/bin:\
/usr/local/sbin:\
/usr/bin:\
/usr/sbin:\
/bin:\
/sbin:\
~/.local/bin

#
# Set the dotfile plugins to load. These correspond to files in
# $DOTFILES_DIR/plugins
#
# shellcheck disable=SC2034
export DOTFILE_PLUGINS=(
    bommie
    cd
    dircolors
    dotfiles
    find
    fzf
    git
    go
    gruf
    less
    ls
    powerline		# half-second startup time
    ps
    python
    ruby
    tmux
    wish
    direnv		# direnv must be initiliazed last
)

#
# Activate ocd dotfiles, load plugins, etc.
#
# Find out where the dotfiles repo is on disk by following the .bashrc link.
# This assumes the dotfiles `install' script has been run which makes the .bashrc
# link.
#
if [ -L ~/.bashrc ]; then
    bashrc_location=$(readlink -f ~/.bashrc)
    dotfiles_dir=${bashrc_location%/rcs/bashrc}
    source "$dotfiles_dir/activate.sh"

    unset bashrc_location
    unset dotfiles_dir
fi
