#!/bin/bash
#
# Loaded for each terminal and sourced for login shells by ~/.bash_profile.
#
# If not running interactively, don't do anything
[ -z "$PS1" ] && return

set -o vi                         # Run bash with vi keys instead of emacs
shopt -s checkwinsize
shopt -s histappend
shopt -s cdspell                  # Let bash help you change directories when you can't spell

export MANPAGER="nvim -c 'set ft=man' -"
export HISTCONTROL=ignoredups
export HISTSIZE=100000
export PROMPT_COMMAND='history -a'
export EDITOR=nvim
export TERM=xterm-256color                  # this is for solarized
export COLUMNS=$COLUMNS                     # hack for powerline-go which was fixed upstream

#
# Set the dotfile plugins to load. These correspond to files in
# $DOTFILES/plugins

#
# shellcheck disable=SC2034
export DOTFILE_PLUGINS=(
    android
    aws
    bommie
    cd
    dircolors
    docker
    dotfiles
    find
    fzf
    gcloud
    git
    go
    gruf
    java
    less
    ls
    opsdb
    powerline-go
    ps
    #nvm
    python
    ruby
    rust
    rvm
    tmux
    virtualgo
    wish
    direnv		# direnv must be initialized last
)

source ~/.dotfiles/load.sh
