
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="agnoster"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(virtualenvwrapper)

source $ZSH/oh-my-zsh.sh

# User configuration
set -o vi # vi on the command line
setopt +o nomatch # no warn on no globs

export EDITOR=vim
export LS_DFLT_ARGS="--color=auto"
export LESS=mqeisz-2XR                      # -R is important for escape sequences
export TERM=xterm-256color                  # this is for solarized/powerline in tmux
export PYTHONDONTWRITEBYTECODE=1            # stop littering
export FZF_DEFAULT_COMMAND='ag -l -g""'     # ag for showing only interesting files
export FZF_CTRL_T_COMAMAND=$FZF_DEFAULT_COMMAND

export PATH=\
/usr/local/bin:\
/usr/local/sbin:\
/usr/bin:\
/usr/sbin:\
/bin:\
/sbin:\
~/bin:\
~/.local/bin:\
~/.rvm/bin

#
# Source the configuration for these dotfiles of which this file is a part.
#
# This assumes the install script has been run and .bashrc is a link pointing
# into the dotfiles repo.
#
zshrc_location=$(readlink -f ~/.zshrc)
dotfiles_dir=${zshrc_location%/rcs/zshrc}
. $dotfiles_dir/config.env

# Setup Gruf to aid working on multiple projects simultaneously
# http://github.com/svrana/gruf
if [ -d ~/repos/gruf ]; then
    source ~/repos/gruf/gruf.rc
fi

# Powerline setup (I like it pretty)
#
# Include powerline in path, it's installed via pip
eval `dircolors ~/.dircolors`
if [ -f ~/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh ]; then
    . ~/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh
fi

# rvm required config
export rvmsudo_secure_path=1
[[ -s "$RVM_PATH/scripts/rvm" ]] && . "$RVM_PATH/scripts/rvm"

export DIRENV_LOG_FORMAT=
eval "$(direnv hook zsh)"
