#!/bin/bash
#
# Loaded for each terminal and sourced for login shells by ~/.bash_profile.
#
# If not running interactively, don't do anything
[ -z "$PS1" ] && return

export MANPAGER="nvim -c 'set ft=man' -"
export HISTCONTROL=ignoredups
export HISTSIZE=100000
export PROMPT_COMMAND='history -a'
export EDITOR=nvim
export TERM=xterm-256color                  # this is for solarized

#
# Set the dotfile plugins to load. These correspond to files in
# $DOTFILES/plugins

#
# shellcheck disable=SC2034
export DOTFILE_PLUGINS=(
    android
    aws
    bash
    cd
    dircolors
    docker
    dotfiles
    find
    fzf
    git
    go
    gruf
    java
    keychain
    k8s
    less
    ls
    powerline-go
    ps
    python
    ruby
    rvm
    systemd
    tmux
    direnv		# direnv must be initialized last
)

source ~/.dotfiles/load.sh

if [[ -n $DISPLAY ]]; then
    # configure this in xorg settings somewhere
    setxkbmap -option caps:ctrl_modifier
fi
