[ -f ~/.bashrc ] && source ~/.bashrc

if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
  # If not using a graphical login, then start up x ourselves
  link=$(readlink -nf /etc/systemd/system/default.target)
  if [ "$link"="/etc/systemd/system/default.target" ]; then
    exec startx
  fi
  echo ooo
fi

