#!/usr/bin/env ruby

require 'webrick'

if ARGV.length > 0
  dir = ARGV.pop
else
  dir = './'
end

root = File.expand_path(dir)
server = WEBrick::HTTPServer.new :Port => 8000, :DocumentRoot => root
trap 'INT' do server.shutdown end
server.start
